import { Routes } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { HomeComponent } from './home/home.component';
import { StockComponent } from './stock/stock.component';
import { CryptoComponent } from './crypto/crypto.component';
import { WatchlistComponent } from './watchlist/watchlist.component';
import { SearchComponent } from './search/search.component';
import { ForexComponent } from './forex/forex.component';
import { LandingComponent } from './landing/landing.component';
import { EtfComponent } from './etf/etf.component';
import { AlertComponent } from './alert/alert.component';
import { SettingsComponent } from './settings/settings.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { SecurityComponent } from './security/security.component';
import { TaxComponent } from './tax/tax.component';
import { FireComponent } from './fire/fire.component';
import { FinancialComponent } from './financial/financial.component';
import { CashComponent } from './cash/cash.component';
import { SalaryComponent } from './salary/salary.component';

export const routes: Routes = [
  { path: '', component: LandingComponent },
  { path: 'login', component: LoginComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'news', component: HomeComponent },
  { path: 'stock', component: StockComponent },
  { path: 'crypto', component: CryptoComponent },
  { path: 'watchlist', component: WatchlistComponent },
  { path: 'search', component: SearchComponent },
  { path: 'forex', component: ForexComponent },
  { path: 'security', component: SecurityComponent },
  { path: 'etf', component: EtfComponent },
  { path: 'cash', component: CashComponent },
  { path: 'alert', component: AlertComponent },
  { path: 'tax', component: TaxComponent },
  { path: 'fire', component: FireComponent },
  { path: 'financial', component: FinancialComponent },
  { path: 'salary', component: SalaryComponent },
  { path: 'settings', component: SettingsComponent }
];
