
--Users
INSERT INTO EOTM_USER (ID,EMAIL, PASSWORD) VALUES (1, 'test', '$2a$10$a4MYVw0l7C.FK1zRQ1C0oeFWVY379hRMS/xpZ78cwe1STQm147Cai'); --pw:test

--Currencies
INSERT INTO EOTM_CURRENCY (ID,NAME) VALUES ('eur', 'euro');
INSERT INTO EOTM_CURRENCY (ID,NAME) VALUES ('usd', 'US dollar');
INSERT INTO EOTM_CURRENCY (ID,NAME) VALUES ('huf', 'forint');

--Coins
INSERT INTO EOTM_COIN (ID,NAME,SYMBOL) VALUES ('polkadot', 'Polkadot', 'dot');
INSERT INTO EOTM_COIN (ID,NAME,SYMBOL) VALUES ('bitcoin', 'Bitcoin', 'btc');
INSERT INTO EOTM_COIN (ID,NAME,SYMBOL) VALUES ('cardano', 'Cardano', 'ada');
INSERT INTO EOTM_COIN (ID,NAME,SYMBOL) VALUES ('ethereum', 'Ethereum', 'eth');

--Payments
INSERT INTO EOTM_COIN_PAYMENT (ID,AMOUNT,CURRENCY_ID) VALUES (1, 10.123, 'eur');
INSERT INTO EOTM_COIN_PAYMENT (ID,AMOUNT,CURRENCY_ID) VALUES (2, 5.66, 'eur');
INSERT INTO EOTM_COIN_PAYMENT (ID,AMOUNT,CURRENCY_ID) VALUES (3, 155.66, 'usd');

--Coin Transactions
INSERT INTO EOTM_COIN_TRANSACTION (ID,BUY_SELL,CREATION_DATE,QUANTITY,TRANSACTION_STRING,COIN_ID,PAYMENT_ID,USER_ID,TRANSACTION_DATE) VALUES (1,'B',CURRENT_TIMESTAMP(),6.77,'Hadwd23HD231','polkadot',1,1,CURRENT_TIMESTAMP());
INSERT INTO EOTM_COIN_TRANSACTION (ID,BUY_SELL,CREATION_DATE,QUANTITY,TRANSACTION_STRING,COIN_ID,PAYMENT_ID,USER_ID,TRANSACTION_DATE) VALUES (2,'B',CURRENT_TIMESTAMP(),96.23,'f44FFFFweqcawd34','cardano',2,1,CURRENT_TIMESTAMP());
INSERT INTO EOTM_COIN_TRANSACTION (ID,BUY_SELL,CREATION_DATE,QUANTITY,TRANSACTION_STRING,COIN_ID,PAYMENT_ID,USER_ID,TRANSACTION_DATE) VALUES (3,'B',CURRENT_TIMESTAMP(),101.22,'kjZhfef321Jzh','polkadot',3,1,CURRENT_TIMESTAMP());

--Configs
INSERT INTO EOTM_CONFIG (CONFIG_KEY,CONFIG_VALUE) VALUES ('COIN_GECKO_URL', 'https://api.coingecko.com/api/v3/');