version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: backend/target/backend-0.0.1-SNAPSHOT
      

