version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - store_test_results:
          path: backend/target/surefire-reports
      - store_artifacts:
          path: backend/target/EOTM.jar
      - store_artifacts:
          path: backend/target/site/jacoco
          destination: test_coverage
      - store_artifacts:
          path: backend/target/checkstyle-result.xml
          destination: checkstyle
      

