version: 2.1
jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean package
      - store_test_results:
          path: backend/target/surefire-reports
      - store_artifacts:
          path: backend/target/EOTM.jar
      - store_artifacts:
          path: backend/target/site/jacoco
          destination: test_coverage
      - store_artifacts:
          path: backend/target/checkstyle-result.xml
          destination: checkstyle
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker buildx build --load --platform linux/amd64 -t $DOCKERHUB_USERNAME/eotm:latest .
            docker push $DOCKERHUB_USERNAME/eotm:latest
      - add_ssh_keys:
          fingerprints:
            - "${DO_FINGERPRINT}"
      - run:
          name: Deploy to DigitalOcean Droplet
          command: |
            ssh $DO_USER@$DO_IP_ADDRESS 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD && docker pull $DOCKERHUB_USERNAME/eotm/latest'

