#docker-compose.yml
version: '3'

services:
  app:
    image: 'thanicz/do:4'
    restart: always
    ports:
      - 8080:8080
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eotmdb
      - SPRING_DATASOURCE_USERNAME=eotmdb
      - SPRING_DATASOURCE_PASSWORD=.
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATA_REDIS_HOST=redis
      - EOTM_KEY=.
  finances:
    image: 'thanicz/finances:0.3'
    ports:
      - 8081:8081
    build:
      context: .
    container_name: finances

  db:
    image: 'amd64/postgres:15-bullseye'
    container_name: db
    environment:
      - POSTGRES_USER=eotmdb
      - POSTGRES_PASSWORD=.
      - POSTGRES_DB=eotmdb
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: no
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    links:
      - app
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
#  teamspeak:
#    image: teamspeak:latest
#    environment:
#      - TS3SERVER_LICENSE=accept
#    volumes:
#      - $PWD/data:/data:rw
#    ports:
#      - '9987:9987/udp'
#      - '30033:30033'
#      - '10011:10011'

