#docker-compose.yml

services:
  app:
    image: 'xx/eotm:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=xx
      - SPRING_DATASOURCE_USERNAME=xx
      - SPRING_DATASOURCE_PASSWORD=xx
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - EOTM_KEY=xx
      - SPRING_DATA_REDIS_HOST=redis
  db:
    image: 'amd64/postgres:15-bullseye'
    container_name: db
    environment:
      - POSTGRES_USER=xx
      - POSTGRES_PASSWORD=xx
      - POSTGRES_DB=xx
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    volumes:
      - ./redis-data:/data
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-www:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  teamspeak:
    image: teamspeak:latest
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./data:/var/ts3server
    ports:
      - '9987:9987/udp'
      - '30033:30033'
      - '10011:10011'