x-app: &app
  image: 'thanicz/eotm:${IMAGE_TAG:-latest}'
  restart: unless-stopped
  stop_grace_period: 40s
  mem_limit: 2g
  depends_on:
    - db
    - redis
  environment:
    - SPRING_DATASOURCE_URL=xx
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - SPRING_DATA_REDIS_HOST=redis
    - SPRING_DATA_REDIS_USERNAME=xx
    - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=65
    - LOGS_PATH=/logs
  secrets:
    - source: db_user
      target: spring.datasource.username
    - source: db_password
      target: spring.datasource.password
    - source: jwt_key
      target: EOTM_KEY
    - source: totp_key
      target: EOTM_TOTP_KEY
    - source: totp_salt
      target: EOTM_TOTP_SALT
    - source: redis_password
      target: spring.data.redis.password
  volumes:
    - ./logs:/logs

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  jwt_key:
    file: ./secrets/jwt_key
  totp_key:
    file: ./secrets/totp_key
  totp_salt:
    file: ./secrets/totp_salt
  redis_password:
    file: ./secrets/redis_password
  redis_acl:
    file: ./secrets/redis.acl

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:
  app_blue:
    <<: [*app, *logging]
    container_name: app_blue
    profiles: ["blue"]
  app_green:
    <<: [*app, *logging]
    container_name: app_green
    profiles: ["green"]
  db:
    <<: *logging
    image: 'postgres:18-trixie'
    container_name: db
    restart: unless-stopped
    mem_limit: 1g
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
      - POSTGRES_DB=xx
    secrets:
      - db_user
      - db_password
    volumes:
       - ./postgres-data:/var/lib/postgresql
  redis:
    <<: *logging
    image: redis:8.10
    container_name: redis
    restart: unless-stopped
    mem_limit: 512m
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec", "--maxmemory", "256mb", "--maxmemory-policy", "allkeys-lru", "--aclfile", "/run/secrets/redis.acl"]
    secrets:
      - source: redis_acl
        target: redis.acl
    volumes:
      - ./redis-data:/data
  nginx:
    <<: *logging
    image: nginx:1.31
    container_name: nginx
    restart: unless-stopped
    mem_limit: 128m
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot-www:/var/www/certbot:ro
    ports:
      - 80:80
      - 443:443
  teamspeak:
    <<: *logging
    image: teamspeak:latest
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - ./data:/var/ts3server
    ports:
      - '9987:9987/udp'
      - '30033:30033'
      - '10011:10011'
